---
title: "Calculate Mortality Rates"
author: "Aarsh"
date: '2022-10-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Global parameters and libraries
```{r lib_glob_parameters}

# libraries
library(readr)
library(dplyr)
library(stringr)
library(magrittr)
library(ggplot2)
library(readr)
library(tidytext)
library(tidyr)
library(tidyverse)
library(sf)
library(usethis)
library(devtools)
library(readxl)

# load and document (for automatic rendering of the roxygen comments into a man file) to keep things updated
devtools::load_all()
devtools::document()

# custom operators
`%notin%` <- Negate(`%in%`)

# global parameters 
gbd_year <- 2019

```


## Merge Relative Risks and Mortality Rates

```{r mergeRelativeRisksAndMortalityRates}

# Read in the cleaned GBD mortality rates file
cleaned_gbd_mortality_rates <- read_csv("./data/intermediate/cleaned_gbd_mortality_rates.csv")

# Read in the cleaned relative risks file
cleaned_relative_risks <- read_csv("./data/intermediate/cleaned_relative_risks.csv")

# join the above 2 cleaned datasets
cleaned_joined_mort_rr_data <- cleaned_gbd_mortality_rates %>%
  left_join(cleaned_relative_risks, by = c("cause", "age_interval"))

# dropping redundant columns and renaming certain columns after dropping the redundancies, then reordering the columns
cleaned_joined_mort_rr_data <- cleaned_joined_mort_rr_data %>%
  select(-c(age_interval_ll.y, age_interval_ul.y)) %>%
  rename(age_interval_ll = age_interval_ll.x, 
         age_interval_ul = age_interval_ul.x) %>%
  select(cause, age_interval, age_interval_ll, age_interval_ul, mortality_rate, pm_level, relative_risk)


```

